# config
set -g mouse on

# bindings
set-option -g status-position top

# rewrite prefix-key
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# makes tmux numbering start from 1
set -g base-index 1 
setw -g pane-base-index 1 

# bind for config reload
bind r source-file ~/.tmux.conf

# split windows
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# go to windows
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# resize windows
bind-key -r -T prefix C-k resize-pane -U 5
bind-key -r -T prefix C-j resize-pane -D 5
bind-key -r -T prefix C-h resize-pane -L 5
bind-key -r -T prefix C-l resize-pane -R 5

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'
