# add ~/.local/bin into the PATH
export PATH="$HOME/.local/bin:$PATH"
# oh-my-zsh path
export ZSH="$HOME/.oh-my-zsh"
# oh-my-zsh
ZSH_THEME="refined"
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
plugins=(git sudo poetry)
source $ZSH/oh-my-zsh.sh
# brew PATH
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

