export ZSH="$HOME/.oh-my-zsh"

export LC_ALL=en_US.UTF-8
export LANG=ru_RU.UTF-8

export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"

# oh-my-zsh
ZSH_THEME="refined"
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
plugins=(git sudo)
source $ZSH/oh-my-zsh.sh

