export ZSH="$HOME/.oh-my-zsh"
export PATH="$HOME/Applications:$PATH"
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:~/go/bin
export PATH=$PATH:~/.local/bin
ZSH_THEME="refined"

source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
plugins=(git sudo)

export LC_ALL=en_US.UTF-8
export LANG=ru_RU.UTF-8
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1

source $ZSH/oh-my-zsh.sh

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"

eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

GOOSE_INSTALL=$HOME/go/bin/goose

function sesh-sessions() {
  {
    exec </dev/tty
    exec <&1
    local session
    session=$(sesh list -t -c | fzf --height 40% --reverse --border-label ' sesh ' --border --prompt '⚡  ')
    [[ -z "$session" ]] && return
    sesh connect $session
  }
}

zle     -N             sesh-sessions
bindkey -M emacs '\es' sesh-sessions
bindkey -M vicmd '\es' sesh-sessions
bindkey -M viins '\es' sesh-sessions


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
